"""initial schema

Revision ID: 3513cabd672e
Revises: 
Create Date: 2026-09-24 14:09:10.025013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3513cabd672e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('index', sa.Integer(), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('slug', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('exercise_id', sqlmodel.sql.sqltypes.AutoString(length=36), nullable=True),
    sa.Column('phase_supported', sa.Boolean(), nullable=False),
    sa.Column('angle_joints', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('down_is_decreasing', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('class_name'),
    sa.UniqueConstraint('index'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('platforms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_platforms_name'), ['name'], unique=True)

    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'device_id', name='uq_device_platform_device')
    )
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_devices_device_id'), ['device_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_devices_platform_id'), ['platform_id'], unique=False)

    op.create_table('phase_models',
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('pt_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('onnx_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('mlpackage_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('meta_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=True),
    sa.Column('window', sa.Integer(), nullable=False),
    sa.Column('stride', sa.Integer(), nullable=False),
    sa.Column('epochs', sa.Integer(), nullable=False),
    sa.Column('lr', sa.Float(), nullable=False),
    sa.Column('num_files', sa.Integer(), nullable=False),
    sa.Column('metrics', sa.JSON(), nullable=False),
    sa.Column('mlflow_run_id', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('exercise_fk', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['exercise_fk'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'class_name', 'version', name='uq_phase_model_version')
    )
    with op.batch_alter_table('phase_models', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_phase_models_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_phase_models_exercise_fk'), ['exercise_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_phase_models_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_phase_models_status'), ['status'], unique=False)

    op.create_table('dataset_files',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('bucket', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('s3_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.Column('phase_labeled', sa.Boolean(), nullable=False),
    sa.Column('trained_in_version', sqlmodel.sql.sqltypes.AutoString(length=32), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('device_fk', sa.Integer(), nullable=False),
    sa.Column('exercise_fk', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['device_fk'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['exercise_fk'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('platform_id', 'filename', name='uq_dataset_platform_filename')
    )
    with op.batch_alter_table('dataset_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_dataset_files_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_files_device_fk'), ['device_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_files_exercise_fk'), ['exercise_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_dataset_files_platform_id'), ['platform_id'], unique=False)

    op.create_table('collect_files',
    sa.Column('filename', sqlmodel.sql.sqltypes.AutoString(length=128), nullable=False),
    sa.Column('class_name', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('csv_bucket', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('csv_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('video_bucket', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('video_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('uploaded', sa.Boolean(), nullable=False),
    sa.Column('video_start', sa.Float(), nullable=True),
    sa.Column('rows', sa.Integer(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(length=16), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('promoted_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform_id', sa.Integer(), nullable=False),
    sa.Column('device_fk', sa.Integer(), nullable=False),
    sa.Column('exercise_fk', sa.Integer(), nullable=True),
    sa.Column('dataset_file_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['dataset_file_id'], ['dataset_files.id'], ),
    sa.ForeignKeyConstraint(['device_fk'], ['devices.id'], ),
    sa.ForeignKeyConstraint(['exercise_fk'], ['exercises.id'], ),
    sa.ForeignKeyConstraint(['platform_id'], ['platforms.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('dataset_file_id'),
    sa.UniqueConstraint('platform_id', 'filename', name='uq_collect_platform_filename')
    )
    with op.batch_alter_table('collect_files', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_collect_files_class_name'), ['class_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_collect_files_device_fk'), ['device_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_collect_files_exercise_fk'), ['exercise_fk'], unique=False)
        batch_op.create_index(batch_op.f('ix_collect_files_platform_id'), ['platform_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_collect_files_status'), ['status'], unique=False)

    op.create_table('phase_model_files',
    sa.Column('phase_model_id', sa.Integer(), nullable=False),
    sa.Column('dataset_file_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_file_id'], ['dataset_files.id'], ),
    sa.ForeignKeyConstraint(['phase_model_id'], ['phase_models.id'], ),
    sa.PrimaryKeyConstraint('phase_model_id', 'dataset_file_id')
    )
    op.create_table('phase_labels',
    sa.Column('data_bucket', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('data_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('video_bucket', sqlmodel.sql.sqltypes.AutoString(length=64), nullable=False),
    sa.Column('video_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('pose_key', sqlmodel.sql.sqltypes.AutoString(length=256), nullable=False),
    sa.Column('phase_summary', sa.JSON(), nullable=False),
    sa.Column('labeled_at', sqlmodel.sql.sqltypes.UTCDateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collect_file_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sqlmodel.sql.sqltypes.UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['collect_file_id'], ['collect_files.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collect_file_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('phase_labels')
    op.drop_table('phase_model_files')
    with op.batch_alter_table('collect_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_collect_files_status'))
        batch_op.drop_index(batch_op.f('ix_collect_files_platform_id'))
        batch_op.drop_index(batch_op.f('ix_collect_files_exercise_fk'))
        batch_op.drop_index(batch_op.f('ix_collect_files_device_fk'))
        batch_op.drop_index(batch_op.f('ix_collect_files_class_name'))

    op.drop_table('collect_files')
    with op.batch_alter_table('dataset_files', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_dataset_files_platform_id'))
        batch_op.drop_index(batch_op.f('ix_dataset_files_exercise_fk'))
        batch_op.drop_index(batch_op.f('ix_dataset_files_device_fk'))
        batch_op.drop_index(batch_op.f('ix_dataset_files_class_name'))

    op.drop_table('dataset_files')
    with op.batch_alter_table('phase_models', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_phase_models_status'))
        batch_op.drop_index(batch_op.f('ix_phase_models_platform_id'))
        batch_op.drop_index(batch_op.f('ix_phase_models_exercise_fk'))
        batch_op.drop_index(batch_op.f('ix_phase_models_class_name'))

    op.drop_table('phase_models')
    with op.batch_alter_table('devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_devices_platform_id'))
        batch_op.drop_index(batch_op.f('ix_devices_device_id'))

    op.drop_table('devices')
    with op.batch_alter_table('platforms', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_platforms_name'))

    op.drop_table('platforms')
    op.drop_table('exercises')
    # ### end Alembic commands ###
